# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "noteconsole.sln"
    - name: Build and Publish as Self-Contained
      run: dotnet publish "noteconsole/noteconsole/noteconsole.csproj" --configuration Release --self-contained true -r win-x64 -o ./publish /p:PublishSingleFile=true
    - name: Test
      run: dotnet test "noteconsole/noteconsole/noteconsole.csproj" --no-build --verbosity normal
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: noteconsole
        path: ./publish/
